[package]
name = "embd-db-map-orgnizr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4.18"
fltk-theme = "0.7.2"
rusqlite = { version = "0.30.0", features = ["bundled"] }
